[build]
  publish = "public"

[[redirects]]
  from = "/"
  to = "https://fireofmaat.wixsite.com/my-site-1/"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "https://turtlebackrobotics.com/"
  status = 200
  force = true
